### ISSUE TITLE
Same item appear twice or more from same user

### ISSUE THREAD

**Issue by Azdingo** [ghostscript3r/poe-trade-official-site-enhancer#11]
Sometimes when a search is triggered using the multi-livesearches, I receive more than one result from the same user for the same item. Then, the first item is "faded out" and the new item is fine.

Is this a websocket problem or something with the script?

**Comment by ghostscript3r** [comment]
Is it systematic (every search result does that)? If not it's completely normal. It happens when someone place an item for sell for the first time and then edit the note with the price. It also happens if he move from tab to tab. You receive two notifications for that. In fact the one that fades is for the item no more available (the one without a price or referring the old tab). I tried reproducing it with some friends and it doesn't seem to happen every time. I imagine there's a sort of buffer behind the websocket, so if the second notification arrives before the first one has been consumed the first doesn't even start.

If this isn't your case and you think you are seeing this too often reopen the issue, I'll try to reproduce the problem.
