### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by cpieprzak** [ghostscript3r/poe-trade-official-site-enhancer#22]
This appears to not respect the rate limiting on item fetches for GGG's official trade website.

**Comment by ThiagoCururu** [comment]
I was having issues using pathofexile.com/trade at Firefox and tried on Edge. Worked flawlessly. Installed Tampermonkey and this script on it because I can't live without it, and started having the same issues I had on Firefox. Guess I found the culprit :(

**Comment by swernerus** [comment]
Go to the settings of the script, and set the "Minimum time between any two requests to the server (milliseconds)" to 2000. Should fix the problem.

**Comment by cpieprzak** [comment]
This works. Closing the issue.

**Comment by swernerus** [comment]
Well, it's just a workaround. The default value should be changed in the script. 500ms seems to be too low for GGG servers.

**Comment by ghostscript3r** [comment]
> Well, it's just a workaround. The default value should be changed in the script. 500ms seems to be too low for GGG servers.

It actually depends if you've been limited or not I think, I go very well with 500, got the problem once in the last month, and it happened soon after this update. I probably was still limited (I didn't use multi live massively but I was using the auto sort, so every normal search was retrieving all 10 result pages at once every time, failing all the time since the change of policy). I tryed using it with 2 secs and I really don't like it. So I prefer people who need it to set it themselves. If my perception is wrong, and most people need an higher value I can surely change it.
