### ISSUE TITLE
Saved searches protection

### ISSUE THREAD

**Issue by redrios** [ghostscript3r/poe-trade-official-site-enhancer#34]
Hi, where are the saved searches saved? cuz today i just cleared the caché, cockies and history of searches (not autocomplete nor site settings), history of downloads, and my 8 or 9 saved searches got lost. I Used this because i can save this searches instead of having a whole folder up of bookmarked searches. The same thing happened when the league upgraded, IDK if the ultimatum files are still there or where they are, help¡?

**Comment by ghostscript3r** [comment]
For the league change the script wasn't working anymore because of some changes to the web app. It's now fixed, try if your searches are back now.
That said, saved searches are saved in the localstorage of your browser. In some clear cache flow that can be erased. 
I have future plans to add an option to sync what I store there (all options are also stored there) to a selectable cloud service (gist, drive, etc...). 
Frankly I don't feel the urgency at the moment, I have a lot more useful improvements that I can't find the time to develop before this one. 
I don't feel it's urgent mainly because I often manually reset my saves when I change build/league, but also because there is a way to save them before cache wipe by exporting/importing them. The export feature could also be improved to create pastebins on the fly so you could easily share searches, another feature I would consider before the cloud sync.
Given my current spare time and the spiralling state of the game, unless there's a lot of people asking for this I fear it will stay as it is.

**Comment by redrios** [comment]
thank you! And i was just worried about the saves, you've done such a huge & kind job, and now i know where to find these. Do ya thing
